version: '3.4'

services:
  rest-with-aspnet-udemy:
    image: rest-with-asp-net-udemy:dev
    container_name: RestWithASPNETUdemy
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "RestWithASPNETUdemy"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2
    volumes:
      - F:\Projetos\RestWithASP-NET5Udemy\RestWithASP-NET5Udemy\02_RestWithASPNETUdemy_Calculadora\RestWithASPNETUdemy\RestWithASPNETUdemy:/app
      - F:\Projetos\RestWithASP-NET5Udemy\RestWithASP-NET5Udemy\02_RestWithASPNETUdemy_Calculadora\RestWithASPNETUdemy:/src
      - C:\Users\erroc\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\erroc\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft\Xamarin\NuGet\:/root/.nuget/fallbackpackages:ro
      - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages2:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages --additionalProbingPath /root/.nuget/fallbackpackages2  \"/app/bin/Debug/net5.0/RestWithASPNETUdemy.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true